admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 5002 }
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: /
                        route:
                          cluster: ipfs_node
                          timeout: 360s
                        # prevent CORS issue
                        request_headers_to_remove:
                          - Origin
                          - User-Agent
                          - Referer
                        response_headers_to_add:
                          - header:
                              key: Access-Control-Allow-Origin
                              value: "*"
                          - header:
                              key: Access-Control-Allow-Methods
                              value: "GET, POST, OPTIONS"
                          - header:
                              key: Access-Control-Allow-Headers
                              value: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
                          - header:
                              key: Access-Control-Expose-Headers
                              value: "Content-Length,Content-Range"
                          - header:
                              key: Access-Control-Allow-Credentials
                              value: "true"
              http_filters:
                - name: envoy.filters.http.cors
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: ipfs_node
      connect_timeout: 0.25s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: ipfs_node
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ipfs_node
                    port_value: 5001